name: Deploy site via Fleek
on: push
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
      NEXT_TELEMETRY_DISABLED: '1'
      WALLETBEAT_URL_ROOT: 'https://beta.walletbeat.eth.limo'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli
      - name: Build & deploy sites
        run: fleek sites deploy
